---
- name: OpenVPN | Restart OpenVPN
  shell: systemctl restart openvpn

- name: OpenVPN | Firewall | Load iptables rules
  command: "{{ openvpn_path_iptables_rules }}"
  when: load_iptables_rules
  changed_when: false
